// Mirror note: tests that need a signed Pro key are skipped here. The signing key
// lives only in the monorepo (keys/license-private.pem); run them there.
// Mirror note: tests that run a script from the monorepo's scripts/ directory are
// skipped here. That directory is not part of a server folder; run them in the monorepo.
// Contract suite for zip. Mechanical assertions only: the invariants of
// servers/zip/SPEC.md that a test can check without judgement.
import { test } from "node:test";
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { REPO, cleanup, client, proKey, sandbox } from "./_client.mjs";

const MAX_DESCRIPTION = 220;
const HARD_MAX_DESCRIPTION = 1200;
const FILE_ARGS = ["path", "paths", "dir", "out_path", "out_dir"];
const IMPERATIVE = /^(Call this tool|Use this)\b/;
const OVER_LENGTH_BASELINE = [];
const NON_IMPERATIVE_BASELINE = [];
const GARBAGE = '[{"id":"a", <<< truncated by a crash';

test.skip("the version is one number: package.json, src/version.ts and serverInfo agree", async (t) => {
  const here = REPO;
  const pkg = JSON.parse(readFileSync(join(here, "package.json"), "utf8"));
  const generated = readFileSync(join(here, "src", "version.ts"), "utf8");
  assert.match(generated, /GENERATED by scripts\/sync-versions\.mjs/, "version.ts must be generated, not hand written");
  assert.match(generated, new RegExp(`export const VERSION = "${pkg.version.replace(/\./g, "\\.")}";`),
    `src/version.ts does not carry ${pkg.version}; run node scripts/sync-versions.mjs`);

  const box = sandbox();
  const c = client({ dataHome: box.dataHome });
  t.after(() => { c.close(); cleanup(box.dir); });
  const info = await c.init();
  assert.equal(info.serverInfo.version, pkg.version, "serverInfo.version must equal the package version");
  assert.equal(info.serverInfo.name, "mcp-zip");

  // The registry entries a client resolves the package through carry the same number.
  for (const file of ["server.json", "server.mcpb.json"]) {
    const j = JSON.parse(readFileSync(join(here, file), "utf8"));
    assert.equal(j.version, pkg.version, `${file} version`);
    for (const p of j.packages ?? []) assert.equal(p.version, pkg.version, `${file} package entry version`);
  }
  // And sync-versions --check passes for the whole repo, so no sibling drifted either.
  execFileSync(process.execPath, [join(REPO, "scripts", "sync-versions.mjs"), "--check"], { encoding: "utf8" });
});

test("stdout carries JSON-RPC only across initialize, tools/list and one call", async (t) => {
  const box = sandbox();
  const c = client({ dataHome: box.dataHome });
  t.after(() => { c.close(); cleanup(box.dir); });
  await c.init();
  await c.tools();
  await c.call("zip_history", {});
  await new Promise((r) => setTimeout(r, 150));

  const lines = [...c.stdoutLines, c.tail].filter((l) => l.trim() !== "");
  assert.ok(lines.length >= 3, `expected at least 3 protocol lines, got ${lines.length}`);
  for (const line of lines) {
    let m;
    try { m = JSON.parse(line); } catch { assert.fail(`non-JSON on stdout: ${JSON.stringify(line.slice(0, 200))}`); }
    assert.equal(m.jsonrpc, "2.0", `stdout line is JSON but not JSON-RPC: ${line.slice(0, 200)}`);
  }
});

test("every tool description is non-empty, single-paragraph and within the ceiling", async (t) => {
  const box = sandbox();
  const c = client({ dataHome: box.dataHome });
  t.after(() => { c.close(); cleanup(box.dir); });
  await c.init();
  const tools = await c.tools();
  assert.equal(tools.length, 9, "tool count changed; update servers/zip/SPEC.md");

  for (const tool of tools) {
    const d = tool.description ?? "";
    assert.ok(d.trim().length > 0, `${tool.name} has no description`);
    assert.equal(d, d.trim(), `${tool.name} description has leading or trailing whitespace`);
    assert.ok(d.length <= HARD_MAX_DESCRIPTION, `${tool.name} description is ${d.length} chars`);
    assert.ok(!/[\u{1F300}-\u{1FAFF}\u{2600}-\u{27BF}]/u.test(d), `${tool.name} description carries an emoji`);
  }
  const over = tools.filter((x) => (x.description ?? "").length > MAX_DESCRIPTION).map((x) => x.name).sort();
  assert.deepEqual(over.filter((n) => !OVER_LENGTH_BASELINE.includes(n)), [], `tool descriptions over ${MAX_DESCRIPTION} chars`);
});

test("a tool that takes a file path opens with an imperative sentence", async (t) => {
  const box = sandbox();
  const c = client({ dataHome: box.dataHome });
  t.after(() => { c.close(); cleanup(box.dir); });
  await c.init();
  const tools = await c.tools();
  const fileTools = tools.filter((x) => Object.keys(x.inputSchema?.properties ?? {}).some((k) => FILE_ARGS.includes(k)));
  assert.ok(fileTools.length >= 5, "every tool that touches the filesystem takes a path argument");
  const offenders = fileTools.filter((x) => !IMPERATIVE.test(x.description ?? "")).map((x) => x.name).sort();
  assert.deepEqual(offenders.filter((n) => !NON_IMPERATIVE_BASELINE.includes(n)), [],
    'file tools whose description does not start with "Call this tool" or "Use this"');
});

test("corrupt store: the garbage is quarantined byte-for-byte and nothing is overwritten", async (t) => {
  const box = sandbox();
  const dir = join(box.dataHome, "mcp-servers", "zip");
  mkdirSync(dir, { recursive: true });
  writeFileSync(join(dir, "archives.json"), GARBAGE);

  const c = client({ dataHome: box.dataHome });
  t.after(() => { c.close(); cleanup(box.dir); });
  await c.init();
  const src = join(box.dir, "src");
  mkdirSync(src, { recursive: true });
  writeFileSync(join(src, "a.txt"), "a");
  const r = await c.call("zip_create", { dir: src, out_path: join(box.dir, "a.zip") });
  assert.equal(r.isError, true, `a corrupt store must refuse, not succeed: ${r.text.slice(0, 300)}`);
  assert.match(r.text, /corrupt|not valid JSON/i, r.text.slice(0, 300));

  const moved = readdirSync(dir).filter((f) => f.startsWith("archives.json.corrupt-"));
  assert.equal(moved.length, 1, JSON.stringify(readdirSync(dir)));
  assert.equal(readFileSync(join(dir, moved[0]), "utf8"), GARBAGE);
  assert.equal(readdirSync(dir).includes("archives.json"), false);
});

test("cap: the free monthly count is the row cap on this server, and it writes no partial file", async (t) => {
  const box = sandbox();
  const dir = join(box.dataHome, "mcp-servers", "zip");
  mkdirSync(dir, { recursive: true });
  const now = new Date().toISOString();
  writeFileSync(join(dir, "archives.json"), JSON.stringify(
    Array.from({ length: 20 }, (_, i) => ({ id: `s${i}`, op: "zip_create", out_path: "/tmp/s.zip", entries: 1, bytes: 10, uncompressed_bytes: 10, created: now })),
  ));
  const c = client({ dataHome: box.dataHome });
  t.after(() => { c.close(); cleanup(box.dir); });
  await c.init();
  const src = join(box.dir, "src");
  mkdirSync(src, { recursive: true });
  writeFileSync(join(src, "a.txt"), "a");
  const out = join(box.dir, "capped.zip");
  const r = await c.call("zip_create", { dir: src, out_path: out });
  assert.match(r.text, /free tier creates 20 archives/);
  assert.equal(readdirSync(box.dir).includes("capped.zip"), false, "a capped call must leave no file");
  assert.equal(JSON.parse(readFileSync(join(dir, "archives.json"), "utf8")).length, 20, "and no register row");

  // Conversion instrument (docs/CONVERSION_INSTRUMENT.md): the /buy link on a cap message
  // must name the tool that produced it, not the prose of the feature. Asserted on the
  // cheapest gate this suite already trips, so it costs no extra server run.
  const wantSrc = "https://mcp.zovo.one/buy/zip?src=zip.zip_create";
  assert.ok(r.text.includes(wantSrc),
    `the zip_create cap message must carry ${wantSrc}, got: ` + r.text.slice(0, 400));
  // The same message must also carry the bundle offer, tagged with the same src plus
  // ".bundle" so a click on the $39 option is never counted as a click on the $19 one.
  const wantBundle = wantSrc.replace(/\/buy\/[^?]+\?src=/, "/buy/bundle?src=") + ".bundle";
  assert.ok(r.text.includes(wantBundle),
    `the same cap message must carry ${wantBundle}, got: ` + r.text.slice(0, 600));
});

test.skip("license_status reports free with no key and pro with a signed key", async (t) => {
  const box = sandbox();
  const free = client({ dataHome: box.dataHome });
  t.after(() => { free.close(); cleanup(box.dir); });
  await free.init();
  const f = await free.call("license_status", {});
  assert.equal(f.isError, false, f.text);
  assert.match(f.text, /"tier":\s*"free"/, f.text.slice(0, 300));

  const key = proKey();
  assert.match(key, /^MCPL1\./);
  const pro = client({ dataHome: join(box.dir, "pro"), key });
  t.after(() => pro.close());
  await pro.init();
  const p = await pro.call("license_status", {});
  assert.match(p.text, /"tier":\s*"pro"/, p.text.slice(0, 300));

  // A key signed for another product must not unlock this one.
  const other = client({ dataHome: join(box.dir, "other"), key: proKey("not-a-real-product") });
  t.after(() => other.close());
  await other.init();
  const o = await other.call("license_status", {});
  assert.match(o.text, /"tier":\s*"free"/, o.text.slice(0, 300));
});
