# Build context: this repository. Self-contained: all @theluckystrike dependencies are
# vendored under vendor/ with their dist committed, so nothing outside this directory is
# needed. Generated by scripts/sync-mirrors.sh; edit that, not this.
FROM node:22-alpine AS build
WORKDIR /app
COPY package.json tsconfig.json ./
COPY vendor ./vendor
COPY src ./src
RUN npm install --no-audit --no-fund && npm run build

FROM node:22-alpine
WORKDIR /app
ENV NODE_ENV=production
COPY package.json ./
COPY vendor ./vendor
COPY --from=build /app/dist ./dist
RUN npm install --omit=dev --no-audit --no-fund
# A stdio MCP server: no port to expose, protocol traffic on stdout only.
CMD ["node", "dist/index.js"]
